### ISSUE TITLE
Grass incorrect moving

### ISSUE THREAD

**Issue by BloodShadow-Git** [daniel-ilett/shaders-botw-grass#4]
If I move plane, sphere, any object with this shader, grass will move by position, but multiplied by 2
![Desktop Screenshot 2024 08 21 - 16 09 40 39](https://github.com/user-attachments/assets/2a858ffc-f108-48cd-905f-5accfd0368b8)
Used: 
Unity: 6000.0.11f1, 
Universal RenderPipeline: 17.0.3
After import unity throw 3 warning at 172, 307, 311, all of them is " implicit truncation of vector type"

**Comment by artem-python** [comment]
I forgot, used: 
Unity: 6000.0.11f1, 
Universal RenderPipeline: 17.0.3
P.S.: After import unity throw 3 warning at 172, 307, 311, all of them is " implicit truncation of vector type"

**Comment by BloodShadow-Git** [comment]
Solution: https://github.com/daniel-ilett/shaders-botw-grass/pull/2
